import Head from "next/head";
import { useState, useEffect } from "react";
import { GetServerSideProps, GetStaticProps } from "next";
import LRUCache from "lru-cache";

import { getAllPostsFromServer, getCategoryCount } from "../lib/utils";
import AudioPlayer from "@/components/Player/Player";
import MainPlayer from "@/components/MainPlayer/MainPlayer";

import css from "../styles/Home.module.scss";

type Post = {
  id: any;
  audioUrl: any;
  title: any;
  date: string;
};

type HomeProps = {
  posts: Post[];
  totalPosts: number;
};

const cache = new LRUCache({
  max: 500, // maximum number of entries
  // maxAge: 1000 * 60 * 60, // maximum age of an entry in milliseconds (1 hour)
});

const DEFAULT_NUMBER_OF_POSTS = 12;

export default function Home({ posts, totalPosts }: HomeProps) {
  const [numberOfPost, setNumberOfPost] = useState<number>(
    DEFAULT_NUMBER_OF_POSTS
  );

  const [selectedAudio, setSelectedAudio] = useState<any>(null);

  const [filteredPost, setFilteredPost] = useState<Post[]>();

  useEffect(() => setFilteredPost(posts), []);

  const filterPosts = (posts: Post[], words: string[]): Post[] => {
    return posts.filter((post) => {
      const title = post.title.rendered.toLowerCase();
      return (
        words.length > 0 &&
        words.every(
          (word) =>
            typeof word === "string" && title.includes(word.toLowerCase())
        )
      );
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={css["input-container"]}>
        <label htmlFor="numberOfPost">Number of posts:</label>
        <input
          id="numberOfPost"
          type="number"
          defaultValue={numberOfPost}
          onChange={(e) => setNumberOfPost(Number(e.target.value))}
        />
      </div>

      <div className={css["input-container"]}>
        <label htmlFor="search">Search:</label>
        <input
          id="search"
          type="text"
          placeholder="Search"
          onChange={(e) => {
            const string = e.target.value;
            const array = string.split(" ");
            setFilteredPost(filterPosts(posts, array));
          }}
        />
      </div>

      {filteredPost &&
        filteredPost.slice(0, numberOfPost).map((post, i) => {
          const { audioUrl, title, date, id } = post;

          return (
            <div key={`item-${i}`}>
              <AudioPlayer
                title={title.rendered}
                src={`https://www.paullowe.org/wp-content/uploads/${audioUrl}`}
                date={date}
                id={id}
                selectAudio={(val: any) => setSelectedAudio(val)}
              />
            </div>
          );
        })}

      <MainPlayer
        title={selectedAudio?.title}
        src={selectedAudio?.src}
        id={selectedAudio?.id}
      />
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const key = "posts";
  const cachedData = cache.get(key);

  if (cachedData) {
    console.log(`Cache hit for key: ${key}`);
    return { props: cachedData };
  }

  const categoriesCount = await getCategoryCount(80);
  const totalPosts = categoriesCount; // assuming total number of posts is the same as the total number of categories

  const numberOfRequests = Math.ceil(totalPosts / 99);
  const promises = [];

  for (let i = 0; i < numberOfRequests; i++) {
    const offset = i * 99;
    promises.push(getAllPostsFromServer(80, 99, offset));
  }

  const postsFromServer = await Promise.all(promises).then((results) =>
    results.flat().map(({ excerpt, title, date, id }) => {
      const pattern = /src="([^"]*)/;
      const match = excerpt.rendered.match(pattern);
      const audioUrl = match
        ? match[1].replace(
            /^(https?:\/\/)?(www\.)?paullowe\.org\/wp-content\/uploads\//,
            ""
          )
        : "";

      return {
        audioUrl: audioUrl,
        title,
        date,
        id,
      };
    })
  );

  const data = {
    posts: postsFromServer,
    totalPosts,
  };

  cache.set(key, { ...data }); // store the data in cache
  console.log(`Cache miss for key: ${key}`);

  return { props: data };
};
